### ISSUE TITLE
交流

### ISSUE THREAD

**Issue by SiYuan-Rao** [moyuwa/wechat_appinfo_wxapkg#3]
可以加个微信请教一下东西吗？

**Comment by moyuwa** [comment]
有项目问题请说吧，微信不方便放上来

**Comment by SiYuan-Rao** [comment]
wechat_app_search.py，就是这个脚本现在还有用吗？感觉现在微信小程序搜索的接口换了，我尝试抓包并未看到文章中搜索小程序的接口。

**Comment by moyuwa** [comment]
PC端和手机端的微信都试试，如果没有那就是接口换了，这个脚本也有3年了
